### ISSUE TITLE
Does not work at the moment.

### ISSUE THREAD

**Issue by DarkVamprism** [ThomasGaubert/zephyr#20] opened 2016-07-07 12:49 UTC
Me and several people have been having trouble with this, connects fine, says test notification has been received and displayed but nothing in the headset.

**Comment by ThomasGaubert** [comment] 2016-07-08 03:51
Thanks for the report! It'd be a huge help if you could upload your log files a [Gist](https://gist.github.com) and link it here.

**Comment by ThomasGaubert** [comment] 2016-07-08 03:58
My apologies, you can find your log file here: `$USER/AppData/Roaming/zephyr/log.log`

**Comment by DarkVamprism** [comment] 2016-07-08 08:25
https://gist.github.com/DarkVamprism/5eb849746f14901d1a88d5c9f4445972#file-log-log

I removed the log.log, then ran it once without SteamVR(accidentally but left it in) and that surprisingly didn't show any errors and also showed that the message was successfully displayed, I then ran it normally after running SteamVR making sure to close it each time in the system tray aswell, and then a third time running it as admin.

I do see the Alerts button inside the SteamVR overlay so I feel it is connecting but yea.

**Comment by ThomasGaubert** [comment] 2016-07-08 17:12
Thanks! I'll look further into this and let you know next steps.

**Comment by xhuytox** [comment] 2016-07-12 03:17
I can confirm that this is currently not working.

**Comment by ThomasGaubert** [comment] 2016-07-12 05:29
@DarkVamprism @xhuytox Thanks for the log! Are y'all running SteamVR Beta by chance? I wonder if  the beta introduced a change which affected Zephyr.

**Comment by xhuytox** [comment] 2016-07-12 05:38
This was my thinking as well, but when I reverted it to the non-Beta version, it still did not work. I don't believe it has anything to do with the Android app since even sending messages from the desktop client and api calls are not working either. Also, the desktop client does see the messages coming from the app, just not displaying it in the HMD.

**Comment by ThomasGaubert** [comment] 2016-07-12 06:40
Yeah, it's definitely the overlay. Unfortunately this is the hardest part for me to debug and develop on with my current setup. I'll keep investigating though.

Thanks for the help!

**Comment by r04r** [comment] 2016-07-12 21:23
New user here and am also running into issues. Not using Steam or SteamVR beta. Here's my log file: https://gist.github.com/r04r/25ad084327df699992110b9d6a14f5d7

**Comment by xhuytox** [comment] 2016-07-15 06:04
Looks like this was a bug on the SteamVR side. Just tested it with the latest SteamVR beta and notifications work now.

http://steamcommunity.com/games/250820/announcements/detail/616248720999238769

**Comment by ThomasGaubert** [comment] 2016-07-15 08:09
Awesome to hear! The notifications interface for OpenVR is sadly not intended for public use quite yet so I guess this type of thing is to be expected.

@DarkVamprism @r04r Does the issue seem to be resolved on the latest SteamVR beta?

**Comment by DarkVamprism** [comment] 2016-07-15 11:07
Oh man I didn't even think of testing other programs to see if the notifications from those worked, I just tested Zephyr and it seams to be working, sorry for the scare, I will definitely be changing my Play Store review.

**Comment by ThomasGaubert** [comment] 2016-07-15 15:17
Glad to hear! No worries on the review, I want to make sure all is working :)

**Comment by ThomasGaubert** [comment] 2016-07-15 15:17
Going ahead and closing this issue for now. In the event that this issue reappears, we can investigate further.

**Closed by ThomasGaubert** 2016-07-15 15:17 UTC
Labels: bug, overlay

**Comment by r04r** [comment] 2016-07-15 18:06
Indeed, SteamVR beta seems to have resolved the issue!
